# CustomResourceDefinition defines a NEW Kubernetes resource
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myapps.demo.example.com   # <plural>.<group>
spec:
  group: demo.example.com         # API group
  scope: Namespaced               # Namespaced or Cluster
  names:
    plural: myapps
    singular: myapp
    kind: MyApp
    shortNames:
      - ma
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                appName:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer

