# ============================================================
# MYSQL SECRETS
# ============================================================
# Secret is used to store SENSITIVE information securely
# Values must be base64 encoded
#
# NOTE:
# echo -n 'root123' | base64
# echo -n 'demo123' | base64
# ============================================================

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw==   # root123
  MYSQL_PASSWORD: ZGVtbzEyMw==         # demo123

