apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache
spec:
  type: ClusterIP              # Internal service
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80

