# ------------------------------------------------------------
# ServiceAccount: apache-sa
# Scope: Namespace-level (apache)
#
# Purpose:
# This ServiceAccount represents the IDENTITY of an application
# (pods / deployments) running inside the apache namespace.
#
# Important:
# - ServiceAccount is used by pods to authenticate to Kubernetes API
# - Permissions are NOT defined here
# - Permissions are assigned using RoleBinding / ClusterRoleBinding
# ------------------------------------------------------------

apiVersion: v1
kind: ServiceAccount
metadata:
  # Name of the ServiceAccount
  name: apache-sa

  # Namespace where this ServiceAccount exists
  namespace: apache

